# Generated by Django 5.0.3 on 2024-03-31 04:58

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('mail', models.EmailField(max_length=254)),
                ('addr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('phrase', models.CharField(max_length=50, unique=True)),
                ('api_version', models.CharField(max_length=20)),
                ('timestamp', models.TimeField(verbose_name='Time')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('lyrics', models.TextField(max_length=2000)),
                ('char_length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SongSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('significant', models.BooleanField()),
                ('sim_score', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='search',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('phrase'), name='search_phrase_case_insensitive_unique', violation_error_message='Search phrase already exists (case insensitive match)'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='song_title_case_insensitive_unique', violation_error_message='Song already exists (case insensitive match)'),
        ),
        migrations.AddField(
            model_name='songsearch',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lyricsapp.search'),
        ),
        migrations.AddField(
            model_name='songsearch',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lyricsapp.song'),
        ),
    ]
