# Generated by Django 5.0.3 on 2024-03-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyricsapp', '0002_alter_song_char_length_alter_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='char_length',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
