# Generated by Django 5.0.3 on 2024-03-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyricsapp', '0003_alter_song_char_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songsearch',
            name='sim_score',
            field=models.FloatField(),
        ),
    ]
