# Generated by Django 5.0.4 on 2024-04-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyricsapp', '0009_alter_search_done_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
