# Generated by Django 5.0.4 on 2024-04-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyricsapp', '0010_delete_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='api_version',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
