# Generated by Django 5.0.4 on 2024-05-12 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyricsapp', '0012_alter_search_phrase'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='search',
            name='search_phrase_case_insensitive_unique',
        ),
    ]
