# Generated by Django 5.0.4 on 2024-05-26 15:27

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyricsapp', '0013_remove_search_search_phrase_case_insensitive_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='song',
            name='song_title_case_insensitive_unique',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='random', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('title', 'artist'), name='song_title_artist_case_insensitive_unique', violation_error_message='Song and artist already exists (case insensitive match)'),
        ),
    ]
