# Generated by Django 5.0.3 on 2024-03-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyricsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='char_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
