# Generated by Django 5.0.3 on 2024-04-06 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyricsapp', '0004_alter_songsearch_sim_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='end_timestamp',
            field=models.TimeField(default=datetime.datetime(2024, 4, 6, 17, 30, 3, 353803), verbose_name='Done Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('DONE', 'DONE')], default='PENDING', help_text='Search status', max_length=10),
        ),
    ]
