# Generated by Django 5.0.3 on 2024-04-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyricsapp', '0005_search_end_timestamp_search_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='songsearch',
            constraint=models.UniqueConstraint(fields=('song_id', 'search_id'), name='composite_pk_song_id_search_id', violation_error_message='Song search already exists'),
        ),
    ]
