# Generated by Django 5.0.3 on 2024-04-07 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyricsapp', '0006_songsearch_composite_pk_song_id_search_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={},
        ),
        migrations.RemoveField(
            model_name='search',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='search',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 6, 20, 1, 16, 970289)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 6, 20, 2, 17, 89774)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songsearch',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 6, 20, 2, 24, 593720)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search',
            name='end_timestamp',
            field=models.DateTimeField(verbose_name='Done Time'),
        ),
    ]
