# Generated by Django 5.0.3 on 2024-04-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyricsapp', '0008_rename_end_timestamp_search_done_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='done_timestamp',
            field=models.DateTimeField(null=True, verbose_name='Done Time'),
        ),
    ]
